name: Auto Deploy to cPanel

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0

    - name: Upload files to cPanel
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: ${{ secrets.FTP_SERVER }}  # Replace with your cPanel FTP server
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
