name: Auto Deploy to cPanel

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0

    - name: Upload files to cPanel
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}  # Replace with your cPanel FTP server
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
